//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class managers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public managers()
        {
            this.employees = new HashSet<employees>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string barCreditCardNumber { get; set; }
        public System.DateTime creditCardExpirationDate { get; set; }
        public int userId { get; set; }
        public int roleId { get; set; }
        public int barId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employees> employees { get; set; }
        public virtual users users { get; set; }
    }
}
