//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.products_by_order = new HashSet<products_by_order>();
        }
    
        public int id { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public double price { get; set; }
        public string pictureId { get; set; }
        public double rate { get; set; }
        public int productTypeId { get; set; }
        public int barId { get; set; }
    
        public virtual bars bars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_by_order> products_by_order { get; set; }
        public virtual products_type products_type { get; set; }
    }
}
