//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tips
    {
        public int id { get; set; }
        public double amount { get; set; }
        public int employeeId { get; set; }
        public int customerId { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual employees employees { get; set; }
    }
}
